pinpoint-hbase:
  container_name: pinpoint-hbase
  hostname: hbase
  image: naver/pinpoint-hbase:1.6.0-SNAPSHOT
  restart: always
  expose:
    - "2181"
  ports:
    - "2181:2181"

pinpoint-collector:
  container_name: pinpoint-collector
  hostname: collector
  image: naver/pinpoint-collector:1.6.0-SNAPSHOT
  restart: always
  expose:
    - "9994"
    - "9995"
    - "9996"
  ports:
    - "9994:9994"
    - "9995:9995/tcp"
    - "9996:9996/tcp"
    - "9995:9995/udp"
    - "9996:9996/udp"
  environment:
    HBASE_HOST: hbase
    HBASE_PORT: 2181
    COLLECTOR_TCP_PORT: 9994
    COLLECTOR_UDP_STAT_LISTEN_PORT: 9995
    COLLECTOR_UDP_SPAN_LISTEN_PORT: 9996
    CLUSTER_ENABLE: 'true'
    CLUSTER_ZOOKEEPER_ADDRESS: hbase
    DISABLE_DEBUG: 'true'
  links:
    - pinpoint-hbase:hbase
 
pinpoint-web:
  container_name: pinpoint-web
  hostname: web
  image: naver/pinpoint-web:1.6.0-SNAPSHOT
  restart: always
  expose:
    - "8080"
  ports:
    - "3080:8080"
  environment:
    HBASE_HOST: hbase
    HBASE_PORT: 2181
    CLUSTER_ENABLE: 'true'
    CLUSTER_ZOOKEEPER_ADDRESS: hbase
    ADMIN_PASSWORD: admin123
    DISABLE_DEBUG: 'true'
  links:
    - pinpoint-hbase:hbase

# only example
#pinpoint-agent:
#  image: naver/pinpoint-agent:1.6.0-SNAPSHOT
#  net: "none"
#  restart: unless-stopped
#  volumes:
#    - /var/container_data/pinpoint-agent/log:/opt/app/pinpoint-agent/log:rw
#  environment:
#    COLLECTOR_IP: 192.168.99.100
#    COLLECTOR_TCP_PORT: 9994
#    COLLECTOR_UDP_STAT_LISTEN_PORT: 9995
#    COLLECTOR_UDP_SPAN_LISTEN_PORT: 9996
#    DISABLE_DEBUG: 'true'
